# Generated by Django 4.1 on 2022-10-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Img", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="img",
            name="username",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
