# Generated by Django 4.1.1 on 2022-09-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Punch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=123456, max_length=20),
            preserve_default=False,
        ),
    ]
